name: NPM & WebP

# 在 Release 发布时 或手动执行

on:
  release:
     types:
       - published

  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    # Clone 仓库
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      # 设置python
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7 
          
      # pip安装requests
      - name: Pip install requests
        run: |
          pip3 install requests
          
      # 推送到telegram
      - name: Post to telegram
        env:
          telegram_token: ${{secrets.telegram_token}}
          user_id: ${{secrets.user_id}}
        run: |
          python3 post2tg.py
  
   
          

          
      
